name: sonarqube
language: php
before_install:
wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip 11
unzip sonar-scanner-cli-3.3.0.1492-linux.zip -d /tmp
script:
